// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAT5Zfzdqva0Bu_hEq8conFHO5OZjc9Ow',
    appId: '1:1064900477063:web:76e3e332e2e8c02c24b822',
    messagingSenderId: '1064900477063',
    projectId: 'shopscan-7811e',
    authDomain: 'shopscan-7811e.firebaseapp.com',
    storageBucket: 'shopscan-7811e.firebasestorage.app',
    measurementId: 'G-BKD5JPS5KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwGwyGAkJVOpMs02nhUJBmonWbhhhERlk',
    appId: '1:1064900477063:android:4b2965d295793d6d24b822',
    messagingSenderId: '1064900477063',
    projectId: 'shopscan-7811e',
    storageBucket: 'shopscan-7811e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOm7bZzfxyuHzwCbxyiB0yQs1KC_shjRI',
    appId: '1:1064900477063:ios:1615431ec51d3fcf24b822',
    messagingSenderId: '1064900477063',
    projectId: 'shopscan-7811e',
    storageBucket: 'shopscan-7811e.firebasestorage.app',
    iosBundleId: 'com.shopscan.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOm7bZzfxyuHzwCbxyiB0yQs1KC_shjRI',
    appId: '1:1064900477063:ios:1615431ec51d3fcf24b822',
    messagingSenderId: '1064900477063',
    projectId: 'shopscan-7811e',
    storageBucket: 'shopscan-7811e.firebasestorage.app',
    iosBundleId: 'com.shopscan.app',
  );
}
